name: mystore
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

#------------------------ PACKAGES -----------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  dio: ^5.5.0
  intl: ^0.19.0
  logger: ^2.3.0
  get_it: ^7.7.0
  equatable: ^2.0.5
  go_router: ^14.2.0
  injectable: ^2.4.2
  url_launcher: ^6.3.0
  path_provider: ^2.1.3
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  isar: ^3.1.0+1
  flutter_bloc: ^8.1.6
  isar_flutter_libs: ^3.1.0+1

# Product Specific

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1
  injectable_generator: ^2.4.2

flutter:
  uses-material-design: true

#------------------ LOCAL ASSETS ------------------#
  assets: 
    - assets/icons/
    - assets/fonts/
    - assets/images/on_boarding_images/
    - assets/images/login_logos/
    - assets/images/animations/
    - assets/logos/

#------------------ LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
