name: mystore
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

#------------------------ PACKAGES -----------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  dio: ^5.5.0
  http: ^1.2.2
  formz: ^0.7.0  
  intl: ^0.19.0
  logger: ^2.3.0
  get_it: ^7.7.0
  lottie: ^3.1.3
  freezed: ^2.5.2
  equatable: ^2.0.5
  go_router: ^14.2.0
  injectable: ^2.4.2
  url_launcher: ^6.3.0
  fluttertoast: ^8.2.8
  path_provider: ^2.1.4
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.9.0
  flutter_stripe: ^11.0.0
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.3.2
  top_snackbar_flutter: ^3.1.0
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.4.1
  internet_connection_checker: ^1.0.0+1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  isar: ^3.1.0+1
  flutter_bloc: ^8.1.6
  isar_flutter_libs: ^3.1.0+1

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  injectable_generator: ^2.4.2

flutter:
  uses-material-design: true

  #------------------ LOCAL ASSETS ------------------#
  assets:
    - assets/.env
    - assets/icons/
    - assets/icons/categories/
    - assets/icons/payment/
    - assets/fonts/
    - assets/images/on_boarding_images/
    - assets/images/login_logos/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/images/reviews/
    - assets/logos/

  #------------------ LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
